spring:
  name: Demo
redis:
  host: localhost
  port: 8080
  password: Abc@123
  jedis:
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 1
      time-out: 3000
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: mybucket

